services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=restaurant'
      - 'POSTGRES_PASSWORD=restaurant'
      - 'POSTGRES_USER=yann'
    ports:
      - '5432'

  adminer:
    image: 'adminer'
    restart: always
    ports:
      - 8086:8080
